### ISSUE TITLE
Please define outside collaborators in code

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/doctrine-migration-version-checker#6]
Hi there

We now have a process to manage github collaborators in code:
https://github.com/ministryofjustice/github-collaborators/blob/main/README.md#github-outside-collaborators

Please follow the procedure described there to grant @fiacrel access to this repository.

If you have any questions, please post in #ask-operations-engineering on Slack.

**Comment by gregtyler** [comment]
We don't know who @fiacrel is, so won't be adding them back in. We're also going to get rid of the repo shortly.
